In [84]:
import statsmodels.api as sm
import numpy as np
import scipy as sp

# 14.32 Problem Set 3

## Problem 5

In [53]:
Y = np.array([[1, 3, 1, 2, 4, 1, 2, 1, 3, 2]]).T
X = np.array([[1, 1, 0, 1, 0, 0, 1, 0, 1, 1]]).T
X = sm.add_constant(X)
n, k = X.shape

### Part C

In [20]:
beta_hat = np.linalg.inv(X.T @ X) @ X.T @ Y

In [21]:
beta_hat

array([[1.75      ],
       [0.41666667]])

### Part D

In [83]:
X.T @ X

array([[10.,  6.],
       [ 6.,  6.]])

In [51]:
SSR = np.sum((Y - X @ beta_hat) ** 2)

In [70]:
(Y - X @ beta_hat).T @ (Y - X @ beta_hat)

array([[9.58333333]])

In [52]:
SSR

9.583333333333336

In [78]:
sigma_hat_squared = SSR / (n - k)

In [79]:
sigma_hat_squared

1.197916666666667

In [80]:
se_a_hat = np.sqrt(sigma_hat_squared * np.linalg.inv(X.T @ X)[0, 0])

In [81]:
se_b_hat = np.sqrt(sigma_hat_squared * np.linalg.inv(X.T @ X)[1, 1])

In [82]:
se_a_hat, se_b_hat

(0.5472468973568209, 0.7064927065755489)

In [101]:
t_stat = (beta_hat[1, 0] - 0)/ se_b_hat

In [102]:
t_stat

0.5897678246195882

In [104]:
p_val = 2 * (1 - sp.stats.t.cdf(t_stat, n - k))

In [105]:
p_val

0.5716229853442711

In [114]:
critical_val = np.abs(sp.stats.t.ppf(0.025, n - k))

In [115]:
critical_val

2.306004135033371

In [117]:
beta_hat[1, 0] - critical_val * se_b_hat, beta_hat[1, 0] + critical_val * se_b_hat

(-1.2125084360674672, 2.0458417694008)

In [68]:
model = sm.OLS(Y, X)
results = model.fit()
print(results.summary())

                            OLS Regression Results                            
Dep. Variable:                      y   R-squared:                       0.042
Model:                            OLS   Adj. R-squared:                 -0.078
Method:                 Least Squares   F-statistic:                    0.3478
Date:                Thu, 14 Mar 2019   Prob (F-statistic):              0.572
Time:                        22:28:58   Log-Likelihood:                -13.977
No. Observations:                  10   AIC:                             31.95
Df Residuals:                       8   BIC:                             32.56
Df Model:                           1                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          1.7500      0.547      3.198      0.0

/usr/local/lib/python3.6/dist-packages/scipy/stats/stats.py:1416: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=10
  "anyway, n=%i" % int(n))


### Part E

In [126]:
Y_m = np.take(Y, np.argwhere(X[:, 1] == 1))

In [127]:
Y_f = np.take(Y, np.argwhere(X[:, 1] == 0))

In [128]:
Y_m

array([[1],
       [3],
       [2],
       [2],
       [3],
       [2]])

In [129]:
Y_f

array([[1],
       [4],
       [1],
       [1]])

In [130]:
Y_m.mean() - Y_f.mean()

0.4166666666666665

In [133]:
Y_f.mean()

1.75